apiVersion: v1
kind: Service
metadata:
  name: redis-dev
spec:
  ports:
    - port: 6379
      name: redis-dev
  clusterIP: None
  selector:
    app: redis-dev
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-dev
spec:
  selector:
    matchLabels:
      app: redis-dev  # has to match .spec.template.metadata.labels
  serviceName: redis-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-dev  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: redis
          image: redislabs/rejson:latest
          imagePullPolicy: Always
          args: ["--appendonly", "yes", "--save", "5", "1", "--save", "2", "2","--loadmodule", "/usr/lib/redis/modules/rejson.so","--loadmodule", "/usr/lib/redis/modules/redisearch.so"]         
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-volume
              mountPath: /data
      nodeSelector:
        node: redis-dev
      volumes:
        - name: redis-volume
          gcePersistentDisk:
            pdName: redis-data-dev
            fsType: ext4
        